---
# Virtualenv settings.
recreate_virtualenv: true
virtualenv_python_version: "{{ base_python_package }}"

# Application settings.
virtualenv_path: "{{ ansistrano_release_path.stdout }}/venv"
backend_project_path: "{{ ansistrano_release_path.stdout }}/backend"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file1: "{{ application_log_dir }}/gunicorn.log"
application_log_file2: "{{ application_log_dir }}/daphne.log"
requirements_file: "{{ backend_project_path }}/requirements.txt"
pip_use_upgrade_flag: false

# Gunicorn settings.
gunicorn_user: "{{ ansible_user }}"
gunicorn_group: www-data
gunicorn_num_workers: 4
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 300

# Nginx settings.
nginx_static_dir: "{{ backend_project_path }}/static/"
nginx_media_dir: "{{ backend_project_path }}/media/"

# Application settings.
django_username: "devxhub"
django_email: "eliyas@devxhub.com"
django_password: "JE86vlSE4xLGIJNDGd66LoAvdfNzvJV7rzUvjik3"
django_settings_file: "backend.settings"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
run_django_db_migrations: true
run_django_collectstatic: true
run_django_user: false

# Django environment variables.
django_environment:
    DJANGO_READ_DOT_ENV_FILE: True
    DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ django_password }}"
    DJANGO_SECRET_KEY: "{{ django_secret_key }}"
    DJANGO_ALLOWED_HOSTS: "{{ backend_server_name }}, {{ frontend_server_name }}"
    TRUSTED_CORS_ORIGINS: "https://{{ frontend_server_name }},https://{{ backend_server_name }},http://localhost,capacitor://localhost,http://localhost:3000"
    DJANGO_ADMIN_URL: "admin/"
    DJANGO_DEBUG: False
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_NAME: "{{ db_name }}"
    DB_USER: "{{ db_user }}"
    DB_PASSWORD: "{{ db_password }}"
    DATABASE_URL: "postgres://{{ db_password }}:{{ db_user }}@127.0.0.1:5432/{{ db_name }}"
    REDIS_URL: "redis://:{{ redis_requirepass }}@{{ redis_bind_interface }}:{{ redis_port }}/0"
    REDIS_HOST: "{{ redis_bind_interface }}"
    REDIS_PASSWORD: "{{ redis_requirepass }}"
    CELERY_BROKER_URL: "redis://:{{ redis_requirepass }}@{{ redis_bind_interface }}:{{ redis_port }}/0"
    MEDIA_ROOT: "{{ nginx_media_dir }}"
    STATIC_ROOT: "{{ nginx_static_dir }}"
    ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL: True
    ENABLE_SSL: False
    JWT_TTL_REQUEST_EMAIL_CHANGE: "1 hour"
    SITE_URL: "https://{{ frontend_server_name }}"
    EMAIL_HOST: "smtp.mailtrap.io"
    EMAIL_HOST_USER: "13bc4660e85fc6"
    EMAIL_HOST_PASSWORD: "1c9d3599238ee5"
    EMAIL_PORT: "2525"
    EMAIL_FROM: "eesteves@odoogap.com"
