---
- hosts: dev
  become: true
  vars_files:
    # - vars/secret.yml
    - vars/main.yml

  environment:
    FNM_DIR: /home/{{ ansible_user }}/{{ fnm_root_suffix }}
    PATH: /home/{{ ansible_user }}/{{ fnm_root_suffix }}/node-versions/{{ fnm_nodejs_versions|first }}/installation/bin:{{ ansible_env.PATH }}

  vars:
    frontend_server_name: oehealth.promptequation.com
    backend_server_name: oehealth-api.promptequation.com
    certbot_certs:
      - domains:
          - oehealth.promptequation.com
          - oehealth-api.promptequation.com
  roles:
    - base
    # - hurricanehrndz.fnm
    # - geerlingguy.redis
    # - geerlingguy.certbot
    # - geerlingguy.postgresql
    - { role: ansistrano.deploy, become: false }
    - nginx
    - backend
    - frontend
